### ISSUE TITLE
Error [csstree-match] BREAK after 15000 iterations

### ISSUE THREAD

**Issue by PavelFil** [css/csso-cli#33]
This CSS code cause error `[csstree-match] BREAK after 15000 iterations`
```css
.selector {
    box-shadow:0 0 0 0 rgba(88,7,126,.122),0 22px 49px 0 rgba(88,7,126,.122),0 88px 88px 0 rgba(88,7,126,.102),0 199px 119px 0 rgba(88,7,126,.059),0 353px 141px 0 rgba(88,7,126,.02),0 552px 154px 0 rgba(88,7,126,0),inset 0 -12px 68px 0 hsla(0,0%,100%,.349);
}
```
This is a valid CSS code.
